# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20170221_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(blank=True, null=True, to='focus.PostTag', verbose_name='标签'),
        ),
    ]
