# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(blank=True, to='focus.PostTag', verbose_name='标签'),
        ),
    ]
