# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0011_comment_reply_comment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='location',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='newuser',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
