# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0013_auto_20170227_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
